# name: Test Docs Build

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches:
#       - main

# jobs:
#   docs:
#     name: Check that docs build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.10"
#       - uses: actions/checkout@v3
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install Poetry
#         uses: snok/install-poetry@v1
#       - name: Install dependencies
#         run: |
#           poetry install --with docs --no-interaction
#       - name: Build docs
#         run: |
#           cd docs
#           make html
