name: continuous-integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop

jobs:
  pre-commit:
    name: Test code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with lint --no-interaction
      - name: flake8
        run: |
          poetry run flake8 .
      - name: isort
        run: |
          poetry run isort pyfredapi
          poetry run isort tests
      - name: black
        run: |
          poetry run black . --check
      - name: mypy
        run: |
          poetry run mypy pyfredapi

  pytest:
    name: Run pytest
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with test --no-interaction
      - name: Test with pytest
        run: |
          poetry run pytest tests/ --vcr-record=none --no-header -vv
