# .github/workflows/lint
name: Linting

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install pyfredapi
        run: |
          poetry install --with lint --no-interaction
      - name: flake8
        run: |
          flake8 .
      - name: isort
        run: |
          isort --check
      - name: black
        run: |
          black . --check
      - name: mypy
        run: |
          mypy pyfredapi
